In [4]:
import os
import glob
import pandas as pd

cwd = os.getcwd()

file_path = glob.glob(os.path.join(cwd, 'dataset', '2016_Building_Energy_Benchmarking.csv'))[0]
df = pd.read_csv(file_path)
df.head()

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,1.156514e+06,3946027.0,12764.52930,1276453.0,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,9.504252e+05,3242851.0,51450.81641,5145082.0,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,1.451544e+07,49526664.0,14938.00000,1493800.0,False,NaN,Compliant,NaN,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,...,8.115253e+05,2768924.0,18112.13086,1811213.0,False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,...,1.573449e+06,5368607.0,88039.98438,8803998.0,False,NaN,Compliant,NaN,505.01,2.88

In [8]:
def drop_columns_by_nan_threshold(df, threshold):
    nan_percentage = df.isna().mean() * 100
    cols_to_drop = nan_percentage[nan_percentage > threshold].index
    df_dropped = df.drop(columns=cols_to_drop)
    dropped_columns_info = {col: nan_percentage[col] for col in cols_to_drop}
    print(f"Dropped columns: {dropped_columns_info}")
    return df_dropped

def drop_columns_by_value_threshold(df, threshold):
    cols_to_drop = []
    dropped_columns_info = {}

    for col in df.columns:
        value_counts = df[col].value_counts(normalize=True) * 100
        if not value_counts.empty and value_counts.iloc[0] > threshold:
            cols_to_drop.append(col)
            top_values = value_counts.head(3).to_dict()
            dropped_columns_info[col] = top_values

    df_dropped = df.drop(columns=cols_to_drop)
    print(f"Dropped columns: {dropped_columns_info}")
    return df_dropped
    

def check_uniqueness(df):
    unique_checks = [
        (['OSEBuildingID'], "OSEBuildingID is unique"),
        (['PropertyName', 'Address'], "Couple (PropertyName, Address) is unique"),
        (['CouncilDistrictCode', 'Neighborhood'], "Combination (CouncilDistrictCode, Neighborhood) has unique ZipCode")
    ]
    
    for columns, message in unique_checks:
        if columns == ['City', 'State']:
            if df.groupby(columns)['ZipCode'].nunique().max() > 1:
                duplicates = df[df.duplicated(subset=columns, keep=False)]
                return duplicates[['CouncilDistrictCode', 'Neighborhood', 'ZipCode']]
        else:
            if df[columns].duplicated(keep=False).any():
                duplicates = df[df.duplicated(subset=columns, keep=False)]
                return duplicates[columns + ['ZipCode']]
    
    return "All checks passed"

threshold = 25
df_cleaned = drop_columns_by_nan_threshold(df, threshold)

threshold_value = 99
df_cleaned_value = drop_columns_by_value_threshold(df_cleaned, threshold_value)

result = check_uniqueness(df_cleaned_value)

if isinstance(result, str):
    df_cleaned = df_cleaned[['OSEBuildingID', 'ZipCode']]
else:
    print(result)

display(df_cleaned.head())

Dropped columns: {'SecondLargestPropertyUseType': np.float64(50.26658767772511), 'SecondLargestPropertyUseTypeGFA': np.float64(50.26658767772511), 'ThirdLargestPropertyUseType': np.float64(82.34597156398105), 'ThirdLargestPropertyUseTypeGFA': np.float64(82.34597156398105), 'YearsENERGYSTARCertified': np.float64(96.47511848341233), 'Comments': np.float64(100.0), 'Outlier': np.float64(99.0521327014218)}
Dropped columns: {'DataYear': {2016: 100.0}, 'City': {'Seattle': 100.0}, 'State': {'WA': 100.0}}
      CouncilDistrictCode           Neighborhood  ZipCode
0                       7               DOWNTOWN  98101.0
1                       7               DOWNTOWN  98101.0
2                       7               DOWNTOWN  98101.0
3                       7               DOWNTOWN  98101.0
4                       7               DOWNTOWN  98121.0
...                   ...                    ...      ...
3371                    2       GREATER DUWAMISH      NaN
3372                    2               DOWNTOWN      NaN
3373                    7  MAGNOLIA / QUEEN ANNE      NaN
3374                    1       GREATER DUWAMISH      NaN
3375                    2       GREATER DUWAMISH      NaN

[3373 rows x 3 columns]

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,SiteEnergyUseWN(kBtu),SteamUse(kBtu),Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,ComplianceStatus,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,7456910.0,2003882.00,1.156514e+06,3946027.0,12764.52930,1276453.0,False,Compliant,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,8664479.0,0.00,9.504252e+05,3242851.0,51450.81641,5145082.0,False,Compliant,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,73937112.0,21566554.00,1.451544e+07,49526664.0,14938.00000,1493800.0,False,Compliant,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,...,6946800.5,2214446.25,8.115253e+05,2768924.0,18112.13086,1811213.0,False,Compliant,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,...,14656503.0,0.00,1.573449e+06,5368607.0,88039.98438,8803998.0,False,Compliant,505.01,2.88

In [5]:
def drop_columns_by_nan_threshold(df, threshold):
    nan_percentage = df.isna().mean() * 100
    cols_to_drop = nan_percentage[nan_percentage > threshold].index
    df_dropped = df.drop(columns=cols_to_drop)
    dropped_columns_info = {col: nan_percentage[col] for col in cols_to_drop}
    print(f"Dropped columns: {dropped_columns_info}")
    return df_dropped

def drop_columns_by_value_threshold(df, threshold):
    cols_to_drop = []
    dropped_columns_info = {}

    for col in df.columns:
        value_counts = df[col].value_counts(normalize=True) * 100
        if not value_counts.empty and value_counts.iloc[0] > threshold:
            cols_to_drop.append(col)
            top_values = value_counts.head(3).to_dict()
            dropped_columns_info[col] = top_values

    df_dropped = df.drop(columns=cols_to_drop)
    print(f"Dropped columns: {dropped_columns_info}")
    return df_dropped
    

def check_uniqueness(df):
    unique_checks = [
        (['OSEBuildingID'], "OSEBuildingID is unique"),
        (['PropertyName', 'Address'], "Couple (PropertyName, Address) is unique"),
        (['CouncilDistrictCode', 'Neighborhood'], "Combination (CouncilDistrictCode, Neighborhood) has unique ZipCode")
    ]
    
    for columns, message in unique_checks:
        if columns == ['City', 'State']:
            if df.groupby(columns)['ZipCode'].nunique().max() > 1:
                duplicates = df[df.duplicated(subset=columns, keep=False)]
                return duplicates[['CouncilDistrictCode', 'Neighborhood', 'ZipCode']]
        else:
            if df[columns].duplicated(keep=False).any():
                duplicates = df[df.duplicated(subset=columns, keep=False)]
                return duplicates[columns + ['ZipCode']]
    
    return "All checks passed"

threshold = 25
df_cleaned = drop_columns_by_nan_threshold(df, threshold)

threshold_value = 99
df_cleaned_value = drop_columns_by_value_threshold(df_cleaned, threshold_value)

result = check_uniqueness(df_cleaned_value)

if isinstance(result, str):
    df_cleaned = df_cleaned[['OSEBuildingID', 'ZipCode']]
else:
    print(result)

display(df_cleaned.head())

AttributeError: 'list' object has no attribute 'tolist'

In [ ]:
def drop_columns_by_nan_threshold(df, threshold):
    nan_percentage = df.isna().mean() * 100
    cols_to_drop = nan_percentage[nan_percentage > threshold].index.tolist()
    df_dropped = df.drop(columns=cols_to_drop)
    print(f"Dropped columns due to NaN threshold: {cols_to_drop}")
    return df_dropped

def drop_columns_by_value_threshold(df, threshold):
    cols_to_drop = [col for col in df.columns if df[col].value_counts(normalize=True).max() * 100 > threshold]
    df_dropped = df.drop(columns=cols_to_drop)
    top_3_values = {col: df[col].value_counts(normalize=True).nlargest(3).values.tolist() for col in cols_to_drop}
    return df_dropped, cols_to_drop, top_3_values

def check_uniqueness(df):
    if df['OSEBuildingID'].duplicated().any():
        duplicates = df[df['OSEBuildingID'].duplicated(keep=False)]
        return duplicates[['OSEBuildingID']].index.tolist(), duplicates['OSEBuildingID'].tolist()
    else:
        print("OSEBuildingID is unique")

    if df.groupby(['PropertyName', 'Address'])['OSEBuildingID'].nunique().max() > 1:
        df_address = df[df.duplicated(subset=['PropertyName', 'Address'], keep=False)]
        df_address = df_address[['OSEBuildingID', 'PropertyName', 'Address']]
        return df_address
    else:
        print("Couple (PropertyName, Address) is unique")
        df = df.drop(columns=['PropertyName', 'Address'], errors='ignore')

    if df.groupby(['CouncilDistrictCode', 'Neighborhood'])['ZipCode'].nunique().max() > 1:
        df_zipcode = df[df.duplicated(subset=['CouncilDistrictCode', 'Neighborhood'], keep=False)]
        df_zipcode = df_zipcode.groupby(['ZipCode', 'CouncilDistrictCode', 'Neighborhood']).size().reset_index(name='Count')
        return df_zipcode
    else:
        print("Combination (CouncilDistrictCode, Neighborhood) has unique ZipCode")
        return df

def clean_and_check_data(df, nan_threshold, value_threshold):
    df_cleaned = drop_columns_by_nan_threshold(df, nan_threshold)
    df_cleaned_value, cols_dropped, top_3_values = drop_columns_by_value_threshold(df_cleaned, value_threshold)
    result = check_uniqueness(df_cleaned_value)

    if isinstance(result, tuple):
        duplicates_indices, duplicates_values = result
        print(f"Duplicate OSEBuildingID indices: {duplicates_indices}")
        print(f"Duplicate OSEBuildingID values: {duplicates_values}")
    elif isinstance(result, pd.DataFrame):
        print("Non-unique combinations found:")
        display(result)
    else:
        print("All uniqueness checks passed.")

    return df_cleaned_value

nan_threshold = 25
value_threshold = 80
df_cleaned_value = clean_and_check_data(df, nan_threshold, value_threshold)
df_cleaned_value.head()